### ISSUE TITLE
Installation assistance needed.

### ISSUE THREAD

**Issue by Sattva-108** [Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API#27]
IDEA version: IntelliJ IDEA 2023.1.3
EmmyLua version: IntelliJ-EmmyLua-1.4.7-IDEA231

Hello, i'm struggling to install it. 
I'm very much new to the IDEA and terminal commands. 
I clicked "Terminal" inside the IntelliJ IDEA and executed how you said, i think. The path is right.

![idea64_doEsHMyJoG](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/03ea28ac-7d51-4df6-a89e-dad262edf11d)

Can you please guide me ? 
This is path, where i put your repo: `"E:\3.3.5\interface\AddOns\unitscan\IntelliJ-IDEA-Lua-IDE-WoW-API-master\GenerateFromAPIDocumentation.lua"
`

Thank you!

**Comment by brittyazel** [comment]
You don't install those scripts. The scripts in the root of the repository are meant for generating the documentation itself and are meant for the admins of this repo to use to keep the repository updated.

To make use of the EmmuLua API sources in this repository you simply clone this repo to your filesystem and add it as an API in your addon project structure. You must also have the Emmylua plugin installed in IntelliJ. You can find a guide on how to set this wiki, albeit slightly out of date: https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/wiki

None of the scripts in this repo are anything you should be executing. This repo is just meant to be sourced by EmmyLua. This repo provides EmmyLua with the class and function definitions it needs for code completion.

**Comment by Sattva-108** [comment]
![idea64_ee1uot7uvf](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/ac92a10f-a40f-4b26-be7f-a94eb9c7e93e)

I think i did install it right, may be i need to do something else? 
It does show documentation for something, i could only find CreateFrame documentation displayed in tooltip. 
![QQL3tAq6tq](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/7e0c193e-bc90-411a-b920-b46cb2c8adc6)

Rest of stuff is missing.
It shows me tooltip like this :
![idea64_VHExY71BmB](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/bcd02a30-6457-4832-8f66-c3968046ba26)

Or like this: 
![idea64_spjiBwfEbE](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/7108128f-8532-43e4-a894-7f9c0a6c18fd)



![idea64_2bXacoScfh](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/f763ce9a-9183-4522-a3a0-3081853bc861)

![idea64_pAGX4Bl1Zn](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/620619ab-1842-4450-b429-3af31e219ad8)

**Comment by Sattva-108** [comment]
I do not have Lua SDK by default even though i have EmmyLua. 
So i tried to add EmmyLua manually via "Add SDK"

![idea64_aiI4yckXwJ](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/db959080-8754-41f8-8466-06cca2adcbad)

And then add the API from this git to the EmmyLua SDK, but that didn't work either.

**Comment by brittyazel** [comment]
Yeah I don't think you did it quite right. To get the "Lua SDK" to show up you need to create a dummy project by going to file > new > project > Lua. Once you make your "dummy" project, IntelliJ should be able to see the Lua SDK across all of your projects.

Then, under your "project structure", you can modify the "Lua" SDK to point to the classpath(s).
![Screenshot 2023-06-26 184516](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/3747347/738f8c4d-5f38-4ea9-8ce3-965334b86b2a)

I'm not sure what you have going on in your screenshots with the .idea showing as an SDK

**Comment by Sattva-108** [comment]
Thank you for quick response, i was able to auto-create Lua SDK and add the `IntelliJ-IDEA-Lua-IDE-WoW-API` and wow source code to it.
![idea64_SD7qWT4h3Y](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/d4c1e94e-421b-4ac3-8fe0-23cad9798b53)

There is no Lua in the dropdown.
What i did is i clicked Lua (see screenshot below) in the menu list on left bottom side to create new project, then the dummy SDK Lua was created automatically. 


![idea64_7KM3mXKYGC](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/b86fe796-2b97-4afe-814f-813fa4c5b9db)

I have though now tried to create new project named Lua, and it didnt seem to help as well.

**Comment by Sattva-108** [comment]
It's funny, but some i'm able to see, some i don't. Im pretty sure that SetScript must be defined in that documentation, but i cannot see its tooltip. 

![qnKhLVD](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/b71faca0-eb0e-4206-a5c9-b57b3f033654)

**Comment by Sattva-108** [comment]
May be it's just not defined, as well for easy functions like SetPoint, SetAllPoints, Hide, Show. And thats why i think that documentation doesn't work?

![idea64_ogEmImxBSP](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/22543953-a1ed-4c6c-977e-f4129bc51a38)

Im able to see the tooltips inside documentation files but not in my addon files.
![LDiGbIh](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/63b6797a-1607-4593-8bb6-005daa5984ce)

**Comment by brittyazel** [comment]
The reason that IsShiftKeyDown() shows mouseover documentation and something like :Show() or :SetPoint() do not is because the first is a standalone function while the other two are class/object functions. I.e. :Show() is a member of the VisibleRegion class and  :SetPoint() is a member of the Region class. Unless you declare your object as a class type that inherits such functionality, it's not going to show (see [here](https://emmylua.github.io/annotations/class.html) and [here](https://emmylua.github.io/annotations/type.html)).

For example, if you follow the flow of inheritance of :Show() or :SetPoint() you will find that the objects implementing them all inherit back to class UIObject. Or if you don't want to go _that_ far back, many inherit from class Frame. I.e. if you declare your frames as type Frame, many of these functions should magically start showing mouseover completion:


```
---@type Frame
local tooltip = CreateFrame("frame", nil, GameTooltip)
```


Further, in the gif you included, another reason you wouldn't be seeing documentation is that you are declaring an entirely new C_ActionBar.IsHelpfulAction() function. You are effectively overwriting the API function with your own, meaning that the documentation from the API no longer applies. What you've done is create a new function of the same name, in which case 'you' would be responsible for supplying the documentation.

**Comment by Sattva-108** [comment]
Alright thank you, it's really hard for me to understand some things.
If i understand you correct, i need to make it like shown on screenshot? 

![idea64_ys66k8LojS](https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/assets/74269253/21437d1c-6bea-4fa2-9497-e1028567bce8)

But i guess that ScrollBar type is not right definition or doesn't exist, so i cannot see tooltips for that class/object functions?
