### ISSUE TITLE
General Wow Addon + Intellij question. 

### ISSUE THREAD

**Issue by Sattva-108** [Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API#28]
I just don't know where else to ask. 
Please **help me** with advice!

Would i somehow be able to transfer all files inside one folder? 
**Why?** 
I want user to open addonname-master and be able to just extract folder inside "addonname"
so he doesnt need to rename from "addonname-master" to "addonname" ? 

For example this has all files in **same root** as README.md :
https://github.com/Sattva-108/TotemTimers-TBC-2.4.3

And this one has all files **inside AdiBags folder** next to README.md
https://github.com/Sattva-108/AdiBags-WoTLK-3.3.5

**Reason:** im editing files right from the addon folder to make testing faster. 

Hope you understand me . Thank you!

**Comment by brittyazel** [comment]
I'm sorry, but I legitimately don't understand what you are asking.

**Comment by Sattva-108** [comment]
Yes i have thought that it would be tricky to understand, as my english is bad and i'm new to github. 
Main reason i want to do this is: 

User downloads the Code zip file and he is seeing "addonname-master" 
So he just puts it in the interface/addons and addon doesn't work.

Many users don't know that they need to rename the folder to just "addonname" for it to work. 
And thats why i would like to have "addonname" folder, which user can just copy without need to renaming the folder and start using addon.

**Comment by brittyazel** [comment]
Having your users download the master branch of your git repository as a delivery mechanism is not a good way to go. Instead you should be using the "Releases" feature of GitHub to have specific releases with a bundled .zip for them to download straight from the release page.

I.e. Something like this: https://github.com/brittyazel/EnhancedRaidFrames/releases/tag/3.5.10

Now, you can manually create the .zip file and upload it as a release asset, or you can use a GitHub Action along with something like the BigWigs Packager. With the BigWigs Packager, all I have to do is create the release, and it will generate the changelog, the .zip asset, and then send my addon to both CurseForge and Wago for inclusion in their repositories.

**Comment by Sattva-108** [comment]
Okay, thanks man, that's reasonable to make the releases.
